apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: django
    tier: frontend
spec:
  ports:
  - port: 80
  selector:
    app: django
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: django
        tier: frontend
    spec:
      containers:
      - name: fe-redis
        image: yasensim/fe-for-redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          # value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          value: env
        - name: REDIS_MASTER_SERVICE_HOST
          value: redis-master.redis-isolated.svc.cluster.local
        - name: REDIS_SLAVE_SERVICE_HOST
          value: redis-slave.redis-isolated.svc.cluster.local
        ports:
        - containerPort: 80
